version: '3.8'

services:
  sentientecho:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
      - FIREWORKS_MODEL_ID=${FIREWORKS_MODEL_ID}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - JINA_AI_API_KEY=${JINA_AI_API_KEY}
      - AGENT_NAME=SentientEcho
      - AGENT_PORT=8000
      - AGENT_HOST=0.0.0.0
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sentientecho
    restart: unless-stopped
    profiles:
      - production
